// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: services.proto

#include "services.pb.h"
#include "services.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace services {

static const char* GameService_method_names[] = {
  "/services.GameService/Stream",
};

std::unique_ptr< GameService::Stub> GameService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< GameService::Stub> stub(new GameService::Stub(channel));
  return stub;
}

GameService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Stream_(GameService_method_names[0], ::grpc::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::services::ServiceMsg, ::services::ServiceMsg>* GameService::Stub::StreamRaw(::grpc::ClientContext* context) {
  return new ::grpc::ClientReaderWriter< ::services::ServiceMsg, ::services::ServiceMsg>(channel_.get(), rpcmethod_Stream_, context);
}

::grpc::ClientAsyncReaderWriter< ::services::ServiceMsg, ::services::ServiceMsg>* GameService::Stub::AsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReaderWriter< ::services::ServiceMsg, ::services::ServiceMsg>(channel_.get(), cq, rpcmethod_Stream_, context, tag);
}

GameService::Service::Service() {
  (void)GameService_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      GameService_method_names[0],
      ::grpc::RpcMethod::BIDI_STREAMING,
      new ::grpc::BidiStreamingHandler< GameService::Service, ::services::ServiceMsg, ::services::ServiceMsg>(
          std::mem_fn(&GameService::Service::Stream), this)));
}

GameService::Service::~Service() {
}

::grpc::Status GameService::Service::Stream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::services::ServiceMsg, ::services::ServiceMsg>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace services

